### ISSUE TITLE
Install command format

### ISSUE THREAD

**Issue by sjanota** [kyma-incubator/kyma-cli#10]
I was thinking about format of install command and came to conclusion that what we have now will lead to problems in future. 

Why is that? `kyma provision ...` requires some provider specific parameters, e.g. `kyma provision gke` would require additional `--domain` flag so it can create appropriate DNS records. On the other hand `kyma install` would also require this parameter. This will lead us to duplication and potential mismatch in cluster and kyma configurations. Moreover, type of the cluster provider is important for installation. Some steps need to be enabled or disabled depending on provider (mostly minikube vs rest of the world). Some features are enabled or not. Some works in a different way.

In my opinion, there are two approaches to make it easier to understand and manage:
1. Store named cluster configuration in `kyma` config. For example one would call `kyma provision local --provider minikube --vm-driver hyperkit` and then reference this cluster in `kyma install --cluster local`.
2. Merge it into one command so instead of calling `kyma provision ...` followed by `kyma install ...` there would be only one call, like those:
   *  `kyma install --provider minikube --minikube-vm-driver hyperkit` or 
   *  `kyma install --provider minikube --skip-provision` or 
   * `kyma install --provider gke --gke-cluster-name my-cluster --domain my.cluster.kyma.org`

I'm leaning towards option 2, as it's a lot simpler. @lilitgh @a-thaler @mszostok What do you think?

**Comment by a-thaler** [comment]
I agree that the domain name is required for both phases which is annoying.
However, your proposals are not feeling sexy to me for now and I have no better idea :(... do you see more parameters as required for both phases in future? To get a better idea of the problem space.. 

I don't like to combine the phases by default as by design kyma should be decoupled fully from the kubernetes cluster. Setting up the cluster you do once in theory and on top you can install/uninstall kyma as you like..
A stored configuration I see as required for configuration of a kyma installation as that can be a quite complex thing which you want to have stored. but probably it should not cover the underlying cluster config..

**Comment by sjanota** [comment]
Already changed
